### ISSUE TITLE
Error opening document template with CustomUI in OpenXML SDK 2.0

### ISSUE THREAD

**Issue by ukalhapu** [OfficeDev/Open-XML-SDK#1138]
**Description**

### Received error while opening document template (.docm) containing  CustomUI part in OpenXML SDK 2.0

**Information**

- .NET Framework 
- DocumentFormat.OpenXml Version: 2.0.5022

Specified argument was out of the range of valid values.   Parameter name: relationshipType
 at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.CreatePartCore(String relationshipType)
at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.CreateOpenXmlPart(String relationshipType)
at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(![image](https://user-images.githubusercontent.com/33087518/159866816-271309ae-a330-44cf-b21f-f56ebddc8c15.png) openXmlPackage, OpenXmlPart sourcePart, PackageRelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load()
at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)

Could you please help to resolve issue ? 

![image](https://user-images.githubusercontent.com/33087518/159867798-c723c98e-462c-40b6-bd51-28405acc8a81.png)

![image](https://user-images.githubusercontent.com/33087518/159868466-26d23da7-9000-4ecf-9a72-ca9ee2de1516.png)
![image](https://user-images.githubusercontent.com/33087518/159868506-94d80a34-c104-41b8-9f57-aa0050ccbd15.png)

**Comment by twsouthwick** [comment]
Please update to the latest version via nuget. v2.0 is somewhere around a decade old at this point :) Latest version is 2.16.0

**Comment by ukalhapu** [comment]
Thanks for the response.
Does latest version 2.16.0 supports opening document template (.docm) containing CustomUI part ?
Is this known issue with v2.0 ?

**Comment by twsouthwick** [comment]
I honestly never used v2.0 so I'm not sure if there are known issues with docm. Can you update to the latest and let us know? If it repros there, we can dig more into it

**Comment by ukalhapu** [comment]
Upgrade to 2.16.0 resolves the issue. 
Thanks for support.
