### ISSUE TITLE
unit test failures on OSX / .NEtCore

### ISSUE THREAD

**Issue by Numpsy** [OfficeDev/Open-XML-SDK#172]
I don't have much time to look at this at the moment, but for the record running the unit tests on the latest source with .Net Core 1.0 on OSX gets me 9 failed tests:

```
xUnit.net .NET CLI test runner (64-bit .NET Core osx.10.11-x64)
  Discovering: DocumentFormat.OpenXml.Tests
  Discovered:  DocumentFormat.OpenXml.Tests
  Starting:    DocumentFormat.OpenXml.Tests
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_MustUnderstand_NonIgnored_UnknownElement [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3767,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat, String path)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(2507,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_MustUnderstand_NonIgnored_UnknownElement()
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_ProcessContent_NonIgnored_UnknownElement [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3726,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(949,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_ProcessContent_NonIgnored_UnknownElement()
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_MultipleChoice_OneFallback_UnPrefixedMCAttributes [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3699,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3370,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_MultipleChoice_OneFallback_UnPrefixedMCAttributes()
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_MultipleChoice_OneFallback_Ignorable [FAIL]
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3726,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3269,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_MultipleChoice_OneFallback_Ignorable()
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_NonIgnored_UnknownElement [FAIL]
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3767,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat, String path)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(249,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_NonIgnored_UnknownElement()
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_OneChoice_MultipleFallback [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3726,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3055,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_OneChoice_MultipleFallback()
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_Preserve_NonIgnored_UnknownElement [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3726,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(1910,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_Preserve_NonIgnored_UnknownElement()
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_ProcessContent_xmlLang [FAIL]
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3726,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(1208,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_ProcessContent_xmlLang()
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
    DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_Preserve_NonIgnored_UnknownAttribute [FAIL]
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/Common/VerifiableLog.cs(162,0): at LogUtil.VerifiableLog.Fail(String message)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(3726,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.validateMC(FileInfo testfile, FileFormatVersions fileformat)
        /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/OpenXmlDomTest/MarkupCompatibilityTest.cs(2068,0): at DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.Validate_Preserve_NonIgnored_UnknownAttribute()
  Finished:    DocumentFormat.OpenXml.Tests
=== TEST EXECUTION SUMMARY ===
   DocumentFormat.OpenXml.Tests  Total: 605, Errors: 0, Failed: 9, Skipped: 0, Time: 140.885s
```

example of a more detailed test failure:

```
New VerifiableLog
Name: Validate_Preserve_NonIgnored_UnknownAttribute
Description: DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest
Comment: Test has been started.
Comment: Opening file:/Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/bin/Debug/netcoreapp1.0/results/d5659965-8b4e-4a76-9bc7-d28810cd1a76/Validate_Preserve_NonIgnored_UnknownAttribute/complex2005_12rtm.docx...
Comment: Loading part:/word/document.xml...
Comment: Host Element: /document@0/body@0
Comment: Target Element:/document@0/body@0/sdt@0
Comment: Executing specified action on host element...
Comment: Executing specified action on target element...
Comment: Skipping setting Ignorable @/document@0/body@0 with value: uns1
Comment: Skipping setting PreserveElements@ /document@0/body@0 with value: uns1:e1uk1
Comment: Setting PreserveAttributes@ /document@0/body@0 with value: uns1:a1uk1
Comment: Closing package...
Validating and Expecting validation error for PreserveAttributes...
Comment: Opening Package /Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/bin/Debug/netcoreapp1.0/results/d5659965-8b4e-4a76-9bc7-d28810cd1a76/Validate_Preserve_NonIgnored_UnknownAttribute/complex2005_12rtm.docx...
Comment: Validating file:/Users/rwebb/Open-XML-SDK/DocumentFormat.OpenXml.Tests/bin/Debug/netcoreapp1.0/results/d5659965-8b4e-4a76-9bc7-d28810cd1a76/Validate_Preserve_NonIgnored_UnknownAttribute/complex2005_12rtm.docx...
Error: Error Message: Type: MarkupCompatibility
Id: MC_InvalidPreserveAttributesAttribute
Description: The PreserveAttributes attribute is invalid - The value 'uns1:a1uk1' contains invalid qualified names. The ProcessAttributes attribute value cannot reference any attribute name that does not belong to a namespace that is identified by the Ignorable attribute of the same element.
Path: /word/document.xml:/w:document[1]/w:body[1]
RelatedNode: :
SemanticConstraintId: 

MC validation error found.
```

Still looking a lot better than it used to though :-)

**Comment by twsouthwick** [comment]
Awesome, @Numpsy. Thanks for giving this a try - we've been discussing the best way to get automated tests running on various platforms. Good to know we've only got 9 failing tests :) (hopefully test issues, and not actual product bugs, though)

**Comment by twsouthwick** [comment]
I ran the current vNext branch on Linux and all tests are passing! Closing issue
