### ISSUE TITLE
WindowsBase crashes when feeding data

### ISSUE THREAD

**Issue by MarcoMartins86** [OfficeDev/Open-XML-SDK#174]
This happens every time, with all versions that are dependent of WindowsBase.dll (2.5, 2.7 not 2.6 since uses independent implementation of System.IO.Packaging).
When feeding a huge amount of data (in my case 137MB of valid XML content into a worksheet part),  throws a System.IO.IsolatedStorage.IsolatedStorageException ("Unable to determine the identity of domain.") 

at System.IO.IsolatedStorage.IsolatedStorage._GetAccountingInfo(Evidence evidence, Type evidenceType, IsolatedStorageScope fAssmDomApp, Object& oNormalized)
   at System.IO.IsolatedStorage.IsolatedStorage.GetAccountingInfo(Evidence evidence, Type evidenceType, IsolatedStorageScope fAssmDomApp, String& typeName, String& instanceName)
   at System.IO.IsolatedStorage.IsolatedStorage._InitStore(IsolatedStorageScope scope, Evidence domainEv, Type domainEvidenceType, Evidence assemEv, Type assemblyEvidenceType, Evidence appEv, Type appEvidenceType)
   at System.IO.IsolatedStorage.IsolatedStorage.InitStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType)
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType)
   at MS.Internal.IO.Packaging.PackagingUtilities.ReliableIsolatedStorageFileFolder.GetCurrentStore()
   at MS.Internal.IO.Packaging.PackagingUtilities.ReliableIsolatedStorageFileFolder..ctor()
   at MS.Internal.IO.Packaging.PackagingUtilities.GetDefaultIsolatedStorageFile()
   at MS.Internal.IO.Packaging.PackagingUtilities.CreateUserScopedIsolatedStorageFileStreamWithRandomName(Int32 retryCount, String& fileName)
   at MS.Internal.IO.Packaging.SparseMemoryStream.EnsureIsolatedStoreStream()
   at MS.Internal.IO.Packaging.SparseMemoryStream.SwitchModeIfNecessary()
   at MS.Internal.IO.Packaging.SparseMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Packaging.DeflateEmulationTransform.Decompress(Stream source, Stream sink)
   at MS.Internal.IO.Packaging.CompressEmulationStream..ctor(Stream baseStream, Stream tempStream, Int64 position, IDeflateTransform transformer)
   at MS.Internal.IO.Packaging.CompressStream.ChangeMode(Mode newMode)
   at MS.Internal.IO.Packaging.CompressStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.Crc32Calculator.CalculateStreamCrc(Stream stream)
   at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.CalculateCrc()
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.UpdateReferences(Boolean closingFlag)
   at MS.Internal.IO.Zip.ZipIOBlockManager.SaveContainer(Boolean closingFlag)
   at MS.Internal.IO.Zip.ZipIOBlockManager.SaveStream(ZipIOLocalFileBlock blockRequestingFlush, Boolean closingFlag)
   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.FeedData(Stream sourceStream)

**Comment by twsouthwick** [comment]
Yes, this is why we moved the dependency to System.IO.Packaging. However, that fix will only show up on .NET Standard 1.3 platform. I took a look, and even on .NET 4.6 (which supports NS 1.3), the net45 one is being used. Unfortunately, we cannot support System.IO.Packaging on <.NET 4.6, but we can add a build to provide a .NET 4.6 version that will have this fix.

@MarcoMartins86 Which platform are you targeting?

@tomjebo We should have a special build for .NET 4.6

**Comment by MarcoMartins86** [comment]
Thanks for the clarification on this subject. For now, because of .Net Framework 4.5 constraints on the project I am working, I will keep using the DocumentFormat.OpenXml 2.6.
In the future when we can migrate to a newer .Net version I will keep this fix in mind.

**Comment by twsouthwick** [comment]
I've updated the library to use the new packaging when targeting .NET 4.6. When you're able to move to .NET Framework 4.6+ please let us know if you are still seeing this issue.

**Comment by BBJ-Artecomm** [comment]
I'm using .NET framework 4.8 with the latest nuget (3.2.0) and I keep getting this same error on big files, how can i solve this ? 
Thanks.
