### ISSUE TITLE
A Stream must be seekable when opening package on .NET Core

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#266]
While refactoring tests, I found that on .NET Core, the following fails, while it succeeds on .NET Framework:

```csharp
using (var stream = TestFileStreams.Presentation)
using (var package = Package.Open(stream))
{
    var openSettings = new OpenSettings
    {
        MarkupCompatibilityProcessSettings = new MarkupCompatibilityProcessSettings(MarkupCompatibilityProcessMode.ProcessAllParts, FileFormatVersions.Office2013)
    };

    using (var doc = PresentationDocument.Open(package, openSettings))
    {
        var v = new OpenXmlValidator(FileFormatVersions.Office2013);
        var errs = v.Validate(doc);

        Assert.Equal(94, errs.Count());
    }
}
```

The input stream needs to be made writeable (ie copied to a `MemoryStream`):

```csharp
using (var stream = TestFileStreams.Presentation.AsMemoryStream())
using (var package = Package.Open(stream))
{
    var openSettings = new OpenSettings
    {
        MarkupCompatibilityProcessSettings = new MarkupCompatibilityProcessSettings(MarkupCompatibilityProcessMode.ProcessAllParts, FileFormatVersions.Office2013)
    };

    using (var doc = PresentationDocument.Open(package, openSettings))
    {
        var v = new OpenXmlValidator(FileFormatVersions.Office2013);
        var errs = v.Validate(doc);

        Assert.Equal(94, errs.Count());
    }
}
```

This fails because `ZipArchive` requires a stream that has read, write, and seek capabilities in .NET Core:

```
Failed   DocumentFormat.OpenXml.Tests.PptxTests01.P005_PptxCreation_Package_Settings
Error Message:
 System.ArgumentException : Update mode requires a stream with read, write, and seek capabilities.
Stack Trace:
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode packageFileMode, FileAccess packageFileAccess)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess)
   at System.IO.Packaging.Package.Open(Stream stream)
   at DocumentFormat.OpenXml.Tests.PptxTests01.P005_PptxCreation_Package_Settings() in C:\Users\tasou\Projects\Software\Open-XML-SDK\DocumentFormat.OpenXml.Tests\TestPptx01.cs:line 60
```

**Comment by twsouthwick** [comment]
This has been fixed as of v4.4.0 of System.IO.Packaging (see https://github.com/dotnet/corefx/commit/4589ecea6de8524d89ed194da52db71c47974722#diff-158b13054282356f81163626ee7d36ad). We should update to the latest System.IO.Packaging to get this fix
