### ISSUE TITLE
Unhandled OpenXmlPackageException when opening workbook which contains malformed email hyperlinks

### ISSUE THREAD

**Issue by dhnc4u** [OfficeDev/Open-XML-SDK#297]
**Description**
An unhandled OpenXmlPackageException exception is thrown by SpreadsheetDocument.Open when the workbook to be opened contains a malformed email hyperlink, such as mailto:one@.
As a result, the xlsx file cannot be opened while it opens fine in Excel.

**Information**
- .NET Target: .NET Framework 4.5.2
- DocumentFormat.OpenXml Version: 2.7.2

**Repro**
In Excel, create a new workbook.
In cell A1, enter random text and add a hyperlink (Right-click > Link).
Select 'E-mail address' and enter an invalid address, such as mailto:one@
Save the file and try to open the file using OpenXml SDK:
var dSpreadsheet = SpreadsheetDocument.Open(fileName, false)

**Observed**
The file cannot be opened with OpenXml SDK, an unhandled 
OpenXmlPackageException exception is thrown and further processing stops.
The file can be opened just fine in Excel.

**Expected**
There should be a way to open such an xlsx.
[issue6b.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/1483879/issue6b.xlsx)

**Comment by twsouthwick** [comment]
This appears to be failing in `System.IO.Packaging` when trying to parse the relationships. The current builds are not wrapping exceptions correctly (fixed in #298) so the error is not easy to find. Here's the stack trace once they are wrapped correctly:

```
Test Name:	DocumentFormat.OpenXml.Tests.ConformanceTest.HyperlinkTests.MalformedHyperlink
Test FullName:	DocumentFormat.OpenXml.Tests.ConformanceTest.HyperlinkTests.MalformedHyperlink
Test Source:	 : line 0
Test Outcome:	Failed
Test Duration:	0:00:00.046

Result StackTrace:	
at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load() in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\OpenXmlPackage.cs:line 413
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.OpenCore(String path, Boolean readWriteMode) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\OpenXmlPackage.cs:line 332
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\ofapi\PackageDocument.cs:line 1295
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\ofapi\PackageDocument.cs:line 1373
   at DocumentFormat.OpenXml.Tests.ConformanceTest.HyperlinkTests.MalformedHyperlink() in [path]\Open-XML-SDK\DocumentFormat.OpenXml.Tests\ConformanceTest\HyperlinkTests.cs:line 16
----- Inner Stack Trace -----
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection.ProcessRelationshipAttributes(XmlCompatibilityReader reader)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection.ParseRelationshipPart(PackagePart part)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection..ctor(Package package, PackagePart part)
   at System.IO.Packaging.PackagePart.EnsureRelationships()
   at System.IO.Packaging.PackagePart.GetRelationshipsHelper(String filterString)
   at System.IO.Packaging.PackagePart.GetRelationships()
   at DocumentFormat.OpenXml.Packaging.PackagePartRelationshipPropertyCollection..ctor(PackagePart packagePart) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\OpenXmlPackage.cs:line 135
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\OpenXmlBasePart.cs:line 110
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\PartContainer.cs:line 2084
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\OpenXmlBasePart.cs:line 111
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts) in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\PartContainer.cs:line 2084
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load() in [path]\Open-XML-SDK\DocumentFormat.OpenXml\src\Framework\OpenXmlPackage.cs:line 407
Result Message:	
DocumentFormat.OpenXml.Packaging.OpenXmlPackageException : Invalid Hyperlink: Malformed URI is embedded as a hyperlink in the document.
---- System.UriFormatException : Invalid URI: The hostname could not be parsed.
```

There's no way we can fix this in the OpenXML SDK project. We may want to look at getting some sort of URI resolver into the System.IO.Packaging library to handle incorrect URI input (this would also help #274)

**Comment by twsouthwick** [comment]
I've added a test that include a repro of this. At this point, the test is supposed to throw an exception (see `DocumentOpenTests.UriExceptionIsWrapped`), but if some sort of URI resolver is implemented, this test will need to be updated

**Comment by abelykh0** [comment]
Is there a reason this was closed? It is a blocking critical issue.

**Comment by twsouthwick** [comment]
@abelykh0 Yeah, that stale bot closed a ton of stuff that should be addressed. I should probably disable it. There's another issue that was opened so we'll just track this there. #715

**Comment by mvarsakelis** [comment]
Was a URI resolver or anything ever implemented to fix this? I've been struggling for 2 days to fix this since I can't tell client to not sent garbage
