### ISSUE TITLE
System.Xml.XmlException thrown when opening SDK-authored document containing an empty URI

### ISSUE THREAD

**Issue by akindle** [OfficeDev/Open-XML-SDK#834]
**Description**

System.Xml.XmlException is thrown when opening a word document that is created by DocumentFormat.OpenXml that contains an empty URI.

**Information**

- .NET Target: Observed on .NET 4.5.2 and 4.7.2
- DocumentFormat.OpenXml Version: 2.12.0

**Repro**

```csharp
using System;
using System.Diagnostics;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Validation;
using DocumentFormat.OpenXml.Wordprocessing;

namespace ConsoleApp5
{
    internal class Program
    {
        private static void Main()
        {
            using (var wordDocument = WordprocessingDocument.Create("test.docx", WordprocessingDocumentType.Document))
            {
                var mainPart = wordDocument.AddMainDocumentPart();
                mainPart.Document = new Document();
                var body = mainPart.Document.AppendChild(new Body());

                var link = mainPart.AddHyperlinkRelationship(new Uri("", UriKind.RelativeOrAbsolute), true);
                body.AppendChild(new Paragraph(new Hyperlink(new Run(new Text("empty URI link"))) {Id = link.Id}));

                var validator = new OpenXmlValidator();
                var errors = validator.Validate(wordDocument);
                foreach (var error in errors)
                {
                    // in this repro, no validation errors occur
                    Debug.Fail($"Document validation error. {error.Description} on node: {error.Node}");
                }
            }

            // System.Xml.XmlException occurs while opening
            using (var wordDocument = WordprocessingDocument.Open("test.docx", false))
            {
                var body = wordDocument.MainDocumentPart.Document.Body;
            }
        }
    }
}
``` 

Alternately, the following test case, similar to https://github.com/OfficeDev/Open-XML-SDK/blob/d2da627a33cf40b0439c4e60465de5c51bfdf2d4/test/DocumentFormat.OpenXml.Tests/ofapiTest/OpenXmlPartTest.cs#L97-L165:
```csharp
        [Fact]
        public void HyperlinkRelationshipTest3()
        {
            using (var stream = new MemoryStream())
            {
                using (var testDocument = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document))
                {
                    var mainPart = testDocument.AddMainDocumentPart();
                    mainPart.Document = new Document();
                    var body = mainPart.Document.AppendChild(new Body());

                    var link = mainPart.AddHyperlinkRelationship(new System.Uri(string.Empty, System.UriKind.RelativeOrAbsolute), true);
                    body.AppendChild(new Paragraph(new Hyperlink(new Run(new Text("empty URI link"))) {Id = link.Id}));

                    var validator = new OpenXmlValidator();
                    var errors = validator.Validate(testDocument);
                    Assert.Empty(errors);
                }

                stream.Seek(0, SeekOrigin.Begin);
                // System.Xml.XmlException occurs while opening
                using (var wordDocument = WordprocessingDocument.Open(stream, false))
                {
                    Assert.Single(wordDocument.MainDocumentPart.HyperlinkRelationships);
                }
            }
        }
```

**Observed**

System.Xml.XmlException: Relationship tag requires attribute 'Target'. Line 1, position 124.
   at MS.Internal.IO.Packaging.InternalRelationshipCollection.ProcessRelationshipAttributes(XmlCompatibilityReader reader)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection.ParseRelationshipPart(PackagePart part)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection..ctor(Package package, PackagePart part)
   at System.IO.Packaging.PackagePart.EnsureRelationships()
   at System.IO.Packaging.PackagePart.GetRelationshipsHelper(String filterString)
   at DocumentFormat.OpenXml.Packaging.PackagePartRelationshipPropertyCollection..ctor(PackagePart packagePart)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary\`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary\`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.OpenCore(String path, Boolean readWriteMode)
   at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
   at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(String path, Boolean isEditable)
   at ConsoleApp5.Program.Main() in Program.cs:line 33

I believe this is the offending xml, from `document.xml.rels`:
`<?xml version="1.0" encoding="utf-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="" TargetMode="External" Id="Re5bd9f7c50024f46" />
</Relationships>`

**Expected**

Xml Validator warning and/or document opened.

**Comment by akindle** [comment]
I believe the root cause of this bug is in `System.IO.Packaging.` System.IO.Packaging.InternalRelationshipCollection considers an empty string to be an invalid URI (https://github.com/dotnet/runtime/blob/7ed93fa9211fcb8719fde13c540a46aa5b5d74fe/src/libraries/System.IO.Packaging/src/System/IO/Packaging/InternalRelationshipCollection.cs#L338-L340), while RFC 3986 states that an empty string is a valid relative URI (https://tools.ietf.org/html/rfc3986#section-4.2). The `URI.TryCreate` check in RelationshipErrorHandler passes, because it considers the empty string to be a valid URI, but later the Packaging library throws an XmlException, because it does not.

I have opened a PR to work around this here (#835), because I suspect that getting a change into System.IO.Packaging would be somewhat more difficult.
