### ISSUE TITLE
Opening an empty docx file leaks handle on Windows.

### ISSUE THREAD

**Issue by Hacnar** [OfficeDev/Open-XML-SDK#930]
Is this a:
- [x] Issue with the OpenXml library
- [ ] Question on library usage

**Description**

When trying to open empty docx file, OpenXml keeps an open handle to this file after throwing an exception. This prevents certain actions from being performed on the file, e.g. deleting it.

**Information**

Tested with
- Windows 10 x64 20H2 build 19042.964
- .NET 5.0.5
- DocumentFormat.OpenXml 2.11.3 and 2.12.3 nuget packages

**Repro**

Create a new, empty docx file and try to open it with OpenXml.

```csharp
void LeakedHandle()
{
    var path = @"F:\aaa.docx";
    using var doc = WordprocessingDocument.Open(path, false);
}
``` 

**Observed**

The method Open throws an exception, which I handle. However, I am unable to delete the file after that.

**Expected**

I can delete the file.

**Comment by twsouthwick** [comment]
Could you try again with 2.13.0? It was just released and I reworked some of the file opening

**Comment by twsouthwick** [comment]
Also, can you paste the full exception you are seeing?

**Comment by Hacnar** [comment]
Behavior is still the same on 2.13.0.

I assumed the exception being thrown is not a bug, because I read that this library does not support opening empty files. My issue is only with the handle leak. Here is the exception:

`System.IO.InvalidDataException: Central Directory corrupt.
 ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file. : 'F:\aaa.docx'
   at System.IO.FileStream.SeekCore(SafeFileHandle fileHandle, Int64 offset, SeekOrigin origin, Boolean closeInvalidHandle)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
   at DocumentFormat.OpenXml.Packaging.PackageLoader.OpenCore(String path, Boolean readWriteMode)
   at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
   at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(String path, Boolean isEditable)
   at TestXmpPackage.Program.WordXml() in F:\test projects\Test\Program.cs:line 42
   at TestXmpPackage.Program.Main(String[] args) in F:\test projects\Test\Program.cs:line 16`

**Comment by twsouthwick** [comment]
This is actually an issue in System.IO.Packaging that was fixed in this commit: https://github.com/dotnet/runtime/pull/46796. You can upgrade to System.IO.Packaging 6.x and it'll be fixed (we'll update our dependency to that at the next big major version bump we do).

For now, you can also put a `GC.Collect()` call in as the handle will be cleaned up by the finalizer as well.
